@echo off
setlocal enabledelayedexpansion

REM ============================================================================
REM ==                Ollama Telegram Bot Interactive Setup                   ==
REM ============================================================================

title Ollama Telegram Bot - Setup

REM --- 1. Check for Python ---
echo Checking for Python...
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Python is not installed or not in PATH.
    echo Please install Python 3.8+ and ensure it's added to your system's PATH.
    echo https://www.python.org/downloads/
    exit /b 1
)
echo Python found.

REM --- 2. Create Virtual Environment ---
if exist ".venv" (
    echo Virtual environment .venv already exists.
    goto :install_deps
)

echo(
echo Creating virtual environment .venv...
python -m venv ".venv"
if %errorlevel% neq 0 (
    echo [ERROR] Failed to create virtual environment.
    exit /b 1
)
echo Virtual environment created.

:install_deps
REM --- 3. Install Dependencies ---
echo(
echo Installing dependencies from requirements.txt...
call ".venv\Scripts\activate.bat"
pip install -r "requirements.txt"
if %errorlevel% neq 0 (
    echo [ERROR] Failed to install dependencies.
    exit /b 1
)
echo Dependencies installed successfully.

REM --- 4. Interactive .env Configuration ---
echo.
echo ===========================================
echo   Configuration Assistant
echo ===========================================
echo Now, I will help you create the .env file.

(
    echo # Ollama Telegram Bot - Environment Configuration
    echo # This file was generated by Setup.bat
) > .env

:ask_token
echo.
echo [1/5] Enter your Telegram Bot Token.
echo       (Get it from @BotFather on Telegram)
set /p BOT_TOKEN="> "
if "%BOT_TOKEN%"=="" goto ask_token
if not "%BOT_TOKEN: =%"=="%BOT_TOKEN%" (
    echo [Validation Error] Token cannot contain spaces. Please try again.
    goto ask_token
)
echo TOKEN=%BOT_TOKEN%>> .env

:ask_admin_id
echo.
echo [2/5] Enter your numeric Telegram User ID to be the admin.
echo       (Get it from @userinfobot on Telegram)
set /p ADMIN_ID="> "
if "%ADMIN_ID%"=="" goto ask_admin_id
set "temp_id=%ADMIN_ID%"
for /l %%a in (0,1,9) do (
    set "temp_id=!temp_id:%%a=!"
)
if not "%temp_id%"=="" (
    echo [Validation Error] The ID must be numeric. Please try again.
    goto ask_admin_id
)
echo ADMIN_IDS=%ADMIN_ID%>> .env

:ask_ollama_url
echo.
echo [3/5] Enter the Ollama server URL (or press Enter to set Default).
echo       (Example: http://192.168.1.10:11434 or localhost)
set /p OLLAMA_BASE_URL="[Default: localhost]> "
if "%OLLAMA_BASE_URL%"=="" set "OLLAMA_BASE_URL=localhost"
echo OLLAMA_BASE_URL=%OLLAMA_BASE_URL%>> .env
echo OLLAMA_PORT=11434>> .env

:ask_groups
echo.
echo [4/5] Allow the bot to be used by anyone in groups?
echo       Enter 1 for YES, or 0 for NO.
set "ALLOW_VAL=0"
set /p ALLOW_VAL="[Default: 0]> "
echo ALLOW_ALL_USERS_IN_GROUPS=!ALLOW_VAL!>>.env

:ask_model  
echo.
echo [5/5] Enter the default Ollama model name.
echo       (To see available models, run 'ollama list' in your terminal)
set /p MODEL_NAME="[Default: qwen3:4b-instruct]> "
if "%MODEL_NAME%"=="" set "MODEL_NAME=qwen3:4b-instruct"
echo INITMODEL=%MODEL_NAME%>> .env

echo TIMEOUT=3000>> .env
echo LOG_LEVEL=INFO>> .env

echo.
echo ===========================================
echo   Setup Complete!
echo ===========================================
echo.
echo The .env file has been created successfully.
echo.
echo You can now start the bot by running:
echo   start.bat
echo.
pause
exit /b 0